CREATE TABLE user
(
    ID            BIGINT AUTO_INCREMENT,
    USERNAME      VARCHAR(30)  NOT NULL,
    EMAIL         VARCHAR(255) NOT NULL,
    PASSWORD      CHAR(60)     NOT NULL,
    PASSWORD_TYPE VARCHAR(30)  NOT NULL,

    2FA           BOOL DEFAULT FALSE,
    2FA_SECRET    VARCHAR(16)  NOT NULL,

    AVATAR_URL    VARCHAR(255) NOT NULL,

    PRIMARY KEY (ID),
    UNIQUE (EMAIL),
    UNIQUE (USERNAME)
);

CREATE TABLE user_2fa_recovery
(
    USER_ID  BIGINT       NOT NULL,

    2FA_CODE VARCHAR(255) NOT NULL,
    VALID    BOOL DEFAULT TRUE,

    PRIMARY KEY (USER_ID, 2FA_CODE),
    FOREIGN KEY (USER_ID) REFERENCES user (ID)
);

CREATE TABLE game
(
    ID   BIGINT AUTO_INCREMENT,

    NAME VARCHAR(255) NOT NULL,
    URL  VARCHAR(255) NOT NULL,

    PRIMARY KEY (ID)
);

CREATE TABLE game_modloader
(
    ID      BIGINT AUTO_INCREMENT,

    GAME_ID BIGINT       NOT NULL,
    NAME    VARCHAR(255) NOT NULL,

    URL     VARCHAR(255) NOT NULL,

    PRIMARY KEY (ID),
    FOREIGN KEY (GAME_ID) REFERENCES game (ID)
);

CREATE TABLE game_version
(
    ID      BIGINT AUTO_INCREMENT,

    GAME_ID BIGINT       NOT NULL,
    VERSION VARCHAR(255) NOT NULL,

    URL     VARCHAR(255) NOT NULL,

    PRIMARY KEY (ID),
    FOREIGN KEY (GAME_ID) REFERENCES game (ID)
);

# Project
CREATE TABLE project
(
    ID              BIGINT AUTO_INCREMENT,
    TITLE           VARCHAR(255)    NOT NULL,

    SUMMARY         VARCHAR(255)    NOT NULL,
    DESCRIPTION     VARCHAR(255)    NOT NULL,
    LOGO_URL        VARCHAR(255)    NOT NULL,
    CACHE_DOWNLOADS BIGINT UNSIGNED NOT NULL,

    CREATED_AT      TIMESTAMP DEFAULT NOW(),
    UPDATED_AT      TIMESTAMP DEFAULT NOW() ON UPDATE NOW(),

    OWNER_ID        BIGINT          NOT NULL,
    GAME_ID         BIGINT          NOT NULL,

    PRIMARY KEY (ID),
    FOREIGN KEY (OWNER_ID) REFERENCES user (ID),
    FOREIGN KEY (GAME_ID) REFERENCES game (ID)
);

CREATE TABLE project_author
(
    ID            BIGINT AUTO_INCREMENT,

    PROJECT_ID    BIGINT       NOT NULL,
    AUTHOR_ID     BIGINT       NOT NULL,

    ROLE          VARCHAR(255) NOT NULL,

    UPLOADED_FILE BOOL DEFAULT FALSE,
    PRIMARY KEY (ID),
    FOREIGN KEY (PROJECT_ID) REFERENCES project (ID),
    FOREIGN KEY (AUTHOR_ID) REFERENCES user (ID)
);

CREATE TABLE project_author_permission
(
    PROJECT_AUTHOR_ID BIGINT       NOT NULL,
    PERMISSION        VARCHAR(255) NOT NULL,

    PRIMARY KEY (PROJECT_AUTHOR_ID, PERMISSION),
    FOREIGN KEY (PROJECT_AUTHOR_ID) REFERENCES project_author (ID)
);

CREATE TABLE project_links
(
    PROJECT_ID BIGINT       NOT NULL,
    TYPE       VARCHAR(255) NOT NULL,
    URL        VARCHAR(255) NOT NULL,

    PRIMARY KEY (PROJECT_ID, TYPE),
    FOREIGN KEY (PROJECT_ID) REFERENCES project (ID)
);

CREATE TABLE project_file
(
    ID         BIGINT AUTO_INCREMENT,

    MD5        VARCHAR(255)    NOT NULL,
    CRC32      VARCHAR(255)    NOT NULL,
    SIZE       BIGINT UNSIGNED NOT NULL,

    CHANGELOG  VARCHAR(255)    NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT NOW(),
    UPDATED_AT TIMESTAMP DEFAULT NOW() ON UPDATE NOW(),

    REVIEWED   BOOL      DEFAULT FALSE,
    RELEASED   BOOL      DEFAULT FALSE,

    PROJECT_ID BIGINT          NOT NULL,
    USER_ID    BIGINT          NOT NULL,

    PRIMARY KEY (ID),
    FOREIGN KEY (PROJECT_ID) REFERENCES project (ID),
    FOREIGN KEY (USER_ID) REFERENCES user (ID)
);

CREATE TABLE project_file_version
(
    PROJECT_FILE_ID BIGINT NOT NULL,
    GAME_VERSION_ID BIGINT NOT NULL,

    PRIMARY KEY (PROJECT_FILE_ID, GAME_VERSION_ID),
    FOREIGN KEY (PROJECT_FILE_ID) REFERENCES project_file (ID),
    FOREIGN KEY (GAME_VERSION_ID) REFERENCES game_version (ID)
);

CREATE TABLE project_file_modloader
(
    PROJECT_FILE_ID BIGINT NOT NULL,
    MODLOADER_ID    BIGINT NOT NULL,

    PRIMARY KEY (PROJECT_FILE_ID, MODLOADER_ID),
    FOREIGN KEY (PROJECT_FILE_ID) REFERENCES project_file (ID),
    FOREIGN KEY (MODLOADER_ID) REFERENCES game_modloader (ID)
);

# Project File Queue
CREATE TABLE project_file_queue
(
    PROJECT_FILE_ID BIGINT       NOT NULL,
    PROCESS_NAME    VARCHAR(255) NOT NULL,

    PRIMARY KEY (PROJECT_FILE_ID, PROCESS_NAME),
    FOREIGN KEY (PROJECT_FILE_ID) REFERENCES project_file (ID)
);

CREATE TABLE nodecraft
(
    ID         VARCHAR(36) NOT NULL,

    CREATED_AT TIMESTAMP DEFAULT NOW(),
    VALID      BOOL      DEFAULT TRUE,

    PRIMARY KEY (ID)
);